// <auto-generated />
using System;
using BuckleUp.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BuckleUp.Migrations
{
    [DbContext(typeof(AppDBContext))]
    partial class AppDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("BuckleUp.Models.Entities.Assessment", b =>
                {
                    b.Property<byte[]>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varbinary(16)");

                    b.Property<byte[]>("CourseId")
                        .IsRequired()
                        .HasColumnType("varbinary(16)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("StopTime")
                        .HasColumnType("datetime");

                    b.Property<byte[]>("TeacherId")
                        .IsRequired()
                        .HasColumnType("varbinary(16)");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("TeacherId");

                    b.ToTable("Assessments");
                });

            modelBuilder.Entity("BuckleUp.Models.Entities.AssessmentQuestion", b =>
                {
                    b.Property<byte[]>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varbinary(16)");

                    b.Property<byte[]>("AssessmentId")
                        .IsRequired()
                        .HasColumnType("varbinary(16)");

                    b.Property<string>("CorrectOption")
                        .HasColumnType("text");

                    b.Property<string>("Option1")
                        .HasColumnType("text");

                    b.Property<string>("Option2")
                        .HasColumnType("text");

                    b.Property<string>("Option3")
                        .HasColumnType("text");

                    b.Property<string>("Option4")
                        .HasColumnType("text");

                    b.Property<string>("QuestionText")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AssessmentId");

                    b.ToTable("AssessmentQuestions");
                });

            modelBuilder.Entity("BuckleUp.Models.Entities.Course", b =>
                {
                    b.Property<byte[]>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varbinary(16)");

                    b.Property<byte[]>("TeacherId")
                        .IsRequired()
                        .HasColumnType("varbinary(16)");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TeacherId");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("BuckleUp.Models.Entities.Group", b =>
                {
                    b.Property<byte[]>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varbinary(16)");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<byte[]>("TeacherId")
                        .IsRequired()
                        .HasColumnType("varbinary(16)");

                    b.HasKey("Id");

                    b.HasIndex("TeacherId");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("BuckleUp.Models.Entities.PersonalUser", b =>
                {
                    b.Property<byte[]>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varbinary(16)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.ToTable("PersonalUsers");
                });

            modelBuilder.Entity("BuckleUp.Models.Entities.Player", b =>
                {
                    b.Property<byte[]>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varbinary(16)");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("BuckleUp.Models.Entities.Quiz", b =>
                {
                    b.Property<byte[]>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varbinary(16)");

                    b.Property<string>("CreatorRole")
                        .HasColumnType("text");

                    b.Property<string>("Link")
                        .HasColumnType("text");

                    b.Property<bool>("ShowPlayerResult")
                        .HasColumnType("tinyint(1)");

                    b.Property<byte[]>("UserId")
                        .IsRequired()
                        .HasColumnType("varbinary(16)");

                    b.Property<string>("status")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Quizzes");
                });

            modelBuilder.Entity("BuckleUp.Models.Entities.QuizPlayer", b =>
                {
                    b.Property<byte[]>("QuizId")
                        .HasColumnType("varbinary(16)");

                    b.Property<byte[]>("PlayerId")
                        .HasColumnType("varbinary(16)");

                    b.Property<bool>("HasPlayed")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.HasKey("QuizId", "PlayerId");

                    b.HasIndex("PlayerId");

                    b.ToTable("QuizPlayer");
                });

            modelBuilder.Entity("BuckleUp.Models.Entities.QuizQuestion", b =>
                {
                    b.Property<byte[]>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varbinary(16)");

                    b.Property<string>("CorrectOption")
                        .HasColumnType("text");

                    b.Property<string>("Option1")
                        .HasColumnType("text");

                    b.Property<string>("Option2")
                        .HasColumnType("text");

                    b.Property<string>("Option3")
                        .HasColumnType("text");

                    b.Property<string>("Option4")
                        .HasColumnType("text");

                    b.Property<string>("QuestionText")
                        .HasColumnType("text");

                    b.Property<byte[]>("QuizId")
                        .IsRequired()
                        .HasColumnType("varbinary(16)");

                    b.HasKey("Id");

                    b.HasIndex("QuizId");

                    b.ToTable("QuizQuestions");
                });

            modelBuilder.Entity("BuckleUp.Models.Entities.Student", b =>
                {
                    b.Property<byte[]>("UserId")
                        .HasColumnName("Id")
                        .HasColumnType("varbinary(16)");

                    b.HasKey("UserId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("BuckleUp.Models.Entities.Teacher", b =>
                {
                    b.Property<byte[]>("UserId")
                        .HasColumnName("Id")
                        .HasColumnType("varbinary(16)");

                    b.HasKey("UserId");

                    b.ToTable("Teachers");
                });

            modelBuilder.Entity("BuckleUp.Models.Entities.User", b =>
                {
                    b.Property<byte[]>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varbinary(16)");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<string>("MiddleName")
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BuckleUp.Models.GroupAssessment", b =>
                {
                    b.Property<byte[]>("GroupId")
                        .HasColumnType("varbinary(16)");

                    b.Property<byte[]>("AssessmentId")
                        .HasColumnType("varbinary(16)");

                    b.HasKey("GroupId", "AssessmentId");

                    b.HasIndex("AssessmentId");

                    b.ToTable("GroupAssessment");
                });

            modelBuilder.Entity("BuckleUp.Models.StudentAssessment", b =>
                {
                    b.Property<byte[]>("StudentId")
                        .HasColumnType("varbinary(16)");

                    b.Property<byte[]>("AssessmentId")
                        .HasColumnType("varbinary(16)");

                    b.Property<bool>("HasTaken")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("NumberOfQuestionsWhenTaken")
                        .HasColumnType("int");

                    b.Property<int>("score")
                        .HasColumnType("int");

                    b.HasKey("StudentId", "AssessmentId");

                    b.HasIndex("AssessmentId");

                    b.ToTable("StudentAssessment");
                });

            modelBuilder.Entity("BuckleUp.Models.StudentCourse", b =>
                {
                    b.Property<byte[]>("StudentId")
                        .HasColumnType("varbinary(16)");

                    b.Property<byte[]>("CourseId")
                        .HasColumnType("varbinary(16)");

                    b.Property<bool>("IsEnrolled")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("StudentId", "CourseId");

                    b.HasIndex("CourseId");

                    b.ToTable("StudentCourse");
                });

            modelBuilder.Entity("BuckleUp.Models.StudentGroup", b =>
                {
                    b.Property<byte[]>("GroupId")
                        .HasColumnType("varbinary(16)");

                    b.Property<byte[]>("StudentId")
                        .HasColumnType("varbinary(16)");

                    b.HasKey("GroupId", "StudentId");

                    b.HasIndex("StudentId");

                    b.ToTable("StudentGroup");
                });

            modelBuilder.Entity("BuckleUp.Models.TeacherStudent", b =>
                {
                    b.Property<byte[]>("TeacherId")
                        .HasColumnType("varbinary(16)");

                    b.Property<byte[]>("StudentId")
                        .HasColumnType("varbinary(16)");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.HasKey("TeacherId", "StudentId");

                    b.HasIndex("StudentId");

                    b.ToTable("TeacherStudent");
                });

            modelBuilder.Entity("BuckleUp.Models.Entities.Assessment", b =>
                {
                    b.HasOne("BuckleUp.Models.Entities.Course", "Course")
                        .WithMany("Assessments")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BuckleUp.Models.Entities.Teacher", "Teacher")
                        .WithMany("Assessments")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BuckleUp.Models.Entities.AssessmentQuestion", b =>
                {
                    b.HasOne("BuckleUp.Models.Entities.Assessment", "Assessment")
                        .WithMany("Questions")
                        .HasForeignKey("AssessmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BuckleUp.Models.Entities.Course", b =>
                {
                    b.HasOne("BuckleUp.Models.Entities.Teacher", "Teacher")
                        .WithMany("Courses")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BuckleUp.Models.Entities.Group", b =>
                {
                    b.HasOne("BuckleUp.Models.Entities.Teacher", "Teacher")
                        .WithMany("Groups")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BuckleUp.Models.Entities.Quiz", b =>
                {
                    b.HasOne("BuckleUp.Models.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BuckleUp.Models.Entities.QuizPlayer", b =>
                {
                    b.HasOne("BuckleUp.Models.Entities.Player", "Player")
                        .WithMany("QuizPlayers")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BuckleUp.Models.Entities.Quiz", "Quiz")
                        .WithMany("QuizPlayers")
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BuckleUp.Models.Entities.QuizQuestion", b =>
                {
                    b.HasOne("BuckleUp.Models.Entities.Quiz", "Quiz")
                        .WithMany("Questions")
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BuckleUp.Models.Entities.Student", b =>
                {
                    b.HasOne("BuckleUp.Models.Entities.User", "User")
                        .WithOne("Student")
                        .HasForeignKey("BuckleUp.Models.Entities.Student", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BuckleUp.Models.Entities.Teacher", b =>
                {
                    b.HasOne("BuckleUp.Models.Entities.User", "User")
                        .WithOne("Teacher")
                        .HasForeignKey("BuckleUp.Models.Entities.Teacher", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BuckleUp.Models.GroupAssessment", b =>
                {
                    b.HasOne("BuckleUp.Models.Entities.Assessment", "Assessment")
                        .WithMany("GroupAssessments")
                        .HasForeignKey("AssessmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BuckleUp.Models.Entities.Group", "Group")
                        .WithMany("GroupAssessments")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BuckleUp.Models.StudentAssessment", b =>
                {
                    b.HasOne("BuckleUp.Models.Entities.Assessment", "Assessment")
                        .WithMany("StudentAssessments")
                        .HasForeignKey("AssessmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BuckleUp.Models.Entities.Student", "Student")
                        .WithMany("StudentAssessments")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BuckleUp.Models.StudentCourse", b =>
                {
                    b.HasOne("BuckleUp.Models.Entities.Course", "Course")
                        .WithMany("StudentCourses")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BuckleUp.Models.Entities.Student", "Student")
                        .WithMany("StudentCourses")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BuckleUp.Models.StudentGroup", b =>
                {
                    b.HasOne("BuckleUp.Models.Entities.Group", "Group")
                        .WithMany("StudentGroups")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BuckleUp.Models.Entities.Student", "Student")
                        .WithMany("StudentGroups")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BuckleUp.Models.TeacherStudent", b =>
                {
                    b.HasOne("BuckleUp.Models.Entities.Student", "Student")
                        .WithMany("TeacherStudents")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BuckleUp.Models.Entities.Teacher", "Teacher")
                        .WithMany("TeacherStudents")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
